name: djicxclusive
favicon: null
layout_spectrum: 0.7681124350056052
typography_spectrum: 0.7971903439611197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08751647057943046
  lightness: 0.27708285627886653
  saturation: 0.9079263715539128
  rhythmicContrast: 0.37529225763864815
purpose: []
